---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
platforms:
  - name: instance
    box: ubuntu/bionic64
provisioner:
  name: ansible
verifier:
  name: ansible
